name: Format (prettier)

on:
    push:
        branches:
          - master
    pull_request:
        branches:
          - master

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Install
              run: yarn add -D prettier

            - name: Run prettier
              run: yarn run prettier:format

            - uses: stefanzweifel/git-auto-commit-action@v2.1.0
              with:
                  commit_message: Prettier was run.
                  branch: master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
