# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: server

on:
  push:
    branches: [stable, canary]
  pull_request:
    branches: [stable, canary]

jobs:
  check-server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i
      - run: nohup npm run dev & sleep 10 && curl http://127.0.0.1:3000/ping
        env:
          CI: true
